### ISSUE TITLE
Installation issue when calling python3 -m pip install PyQt

### ISSUE THREAD

**Issue by hernanrr** [sededu/sededu#98]
Attempting to install from Pypi with Pip, using python3 -m pip install pyqt results in the error shown below.

(vent) % python3 -m pip install pyqt         
ERROR: Could not find a version that satisfies the requirement pyqt (from versions: none)
ERROR: No matching distribution found for pyqt
Attempting python3 -m pip install pyqt5 works as expected.

The installation failure seems to be expected behavior, as it is preempted in the installation instructions. If that is the case, why not simply remove it?

Operating system: MacOS Big Sur Version 11.6.
Installation method: Advanced user installations: Install with pip

**Comment by amoodie** [comment]
Thank you for pointing this out. Installation instructions are updated with v1.1.10.

Installation for `pyqt` is tricky, because the package names change with major version (e.g., `pyqt4`, vs `pyqt5`) and differ between platforms. For example, on `conda`, `pyqt` will install the latest `pyqt5` version, but on `pip` you need to name the version (as you identified).

I've revised the installation instructions to reflect this discrepancy if `pip` installing, and added an `environment.yml` file to make the `pip` `requirements.txt` separate from the `conda` requirements list.
